### ISSUE TITLE
Add bin/debug to gitignore

### ISSUE THREAD

**Issue by arif-hanif** [design-technology/OpenAEC#3]
add folders to the git ignore file

**Comment by ksobon** [comment]
Great catch. Here's a link for reference. http://stackoverflow.com/questions/1470572/gitignore-ignore-any-bin-directory I will try and take care of that tomorrow.

**Comment by ksobon** [comment]
should be taken care of now. It should be ignoring anything in bin\ directory and its all sub-directories.
